### ISSUE TITLE
Improve documentation for a better GitHub landing page

### ISSUE THREAD

**Issue by seidior** [Paryssatis/crochet-stitch-tracker#12]
### Describe the Feature / Enhancement

Building out `README.md` with relevant documentation (and potentially a screenshot) will help explain the project to newcomers that don't have any context for what this project is all about.

### Additional Details and Resources

See [hunnybee-website](https://github.com/hunnybee-website/hunnybee-website.github.io) for an example, and see [this FreeCodeCamp article](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/) for content suggestions.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by Paryssatis** [comment]
Updated: https://github.com/Paryssatis/crochet-stitch-tracker
