### ISSUE TITLE
Add code linting

### ISSUE THREAD

**Issue by seidior** [Paryssatis/crochet-stitch-tracker#13]
### Describe the Feature / Enhancement

The most common tool to add code linting to ensure you're writing clean, standards-compliant code would be [ESLint](https://eslint.org).

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by Paryssatis** [comment]
Solved by #23

**Comment by Paryssatis** [comment]
Havent added any scripts for the tools in package.json

**Comment by Paryssatis** [comment]
Resolved by #24
