### ISSUE TITLE
Add code formatting tool

### ISSUE THREAD

**Issue by seidior** [Paryssatis/crochet-stitch-tracker#14]
### Describe the Feature / Enhancement

The most common tool to add code formatting to ensure you're writing consistent, well-formatted code would be [Prettier](https://prettier.io).

### Additional Details and Resources

In addition, consider adding an [.editorconfig](https://editorconfig.org) file.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by Paryssatis** [comment]
Solved by #23

**Comment by Paryssatis** [comment]
Havent added any scripts for the tools in package.json

**Comment by Paryssatis** [comment]
Resolved by #24
