### ISSUE TITLE
Add .gitignore file to prevent unnecessary files from being committed

### ISSUE THREAD

**Issue by seidior** [Paryssatis/crochet-stitch-tracker#8]
### Describe the Feature / Enhancement

Adding a `.gitignore` file in the root directory of the project would help to prevent any unnecessary files from being committed in the future.

### Additional Details and Resources

[gitignore.io](https://www.toptal.com/developers/gitignore) is a common go-to resource for generating a `.gitignore` file. If using that resource, I would recommend choosing these options: "node,macos"

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by Paryssatis** [comment]
Solved by pull request #20
